### PR TITLE
Update Stable to v6.0.0 on dev

### PR DESCRIPTION
**Pull request by ashleighgregory**
## Description
  - v6.0.0 was released on 04-29-2020
  - update stable on dev

## Issues:

 https://github.com/vulk/cncf_ci/issues/343

## How has this been tested:

 - [ ]  Covered by existing integration testing
 - [ ]  Added integration testing to cover
 - [ ]  Tested with trigger client against
   - [ ]  cidev.cncf.ci
   - [ ]  dev.cncf.ci
   - [ ]  staging.cncf.ci
   - [ ]  cncf.ci (production)
 - [ ]  Browser tested on staging.cncf.ci
 - [x]  Have not tested

## Types of changes:
 - [ ]  Bug fix (non-breaking change which fixes an issue)
 - [ ]  New feature (non-breaking change which adds functionality)
 - [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Version update

## Checklist:
  - [ ]  My change requires a change to the documentation
  - [ ]  I have updated the documentation accordingly
  - [x]  No updates required

### CODE REVIEW

**Comment by ashleighgregory** [comment]
@lixuna - I am not seeing V6.0.0 in the build pipeline.  Only v6.0.0-rc.1 and v6.0.20200429

Screen Shot 2020-05-05 at 6 07 51 PM

**Comment by lixuna** [comment]
@ashleighgregory Vitess has not created a tag for `v6.0.0` yet. The latest is `v5.0.1`

**Comment by lixuna** [comment]
v5.0.1 has been added to dev by will.

**Comment by ashleighgregory** [comment]
Thanks @lixuna.  Please can you provide a link to their correct release page.

I have the two below.  One doesn't list anything and the other I understood at V6.0.0.  I'm obviously looking in the wrong place.  

- https://github.com/crosscloudci/vitess-configuration/releases
- https://github.com/vitessio/vitess/releases

Thanks for sharing so I can update my notes.

**Pull request merged**
